export const profile = {
  name: 'Pranav V.',
  fullName: 'Pranav Venu',
  location: 'Bengaluru, India',
  localSearchLocation: 'Bengaluru / Bangalore / Blore',
  email: 'pranavv736@gmail.com',
  academicEmail: 'prv22aiml@cmrit.ac.in',
  phone: '+917676858328',
  github: 'https://github.com/pranavv1210',
  linkedin: 'https://www.linkedin.com/in/pranav-venu-550729264/',
  resume: '/Pranav_V_Resume.pdf',
  contactHref:
    'mailto:pranavv736@gmail.com?subject=Portfolio%20conversation%20with%20Pranav&body=Hi%20Pranav%2C%0D%0A%0D%0AI%20saw%20your%20portfolio%20and%20wanted%20to%20connect%20about%3A%0D%0A',
  status: 'Building',
  focus: 'AI + product systems',
  summary:
    'Machine Learning Engineer and creative frontend builder from Bengaluru, studying Artificial Intelligence and Machine Learning at CMR Institute of Technology.',
  resumeSkills: [
    'Machine Learning',
    'Deep Learning',
    'Computer Vision',
    'NLP',
    'TensorFlow',
    'Keras',
    'TensorFlow Lite',
    'OpenCV',
    'Python',
    'Java',
    'SQL',
    'React.js',
    'Node.js',
    'HTML',
    'CSS',
    'Power BI',
    'Tableau',
    'Jupyter Notebook',
    'Android Studio',
    'Git',
    'GitHub',
    'AWS',
  ],
  achievements: [
    'Patent filed for an AI-powered pet monitoring system using computer vision',
    'CMRIT hackathon participant across Gen AI, Ops-Fusion, and Vyuhatech 2.0',
  ],
  education: [
    {
      year: '2026',
      label: 'B.E. Artificial Intelligence and Machine Learning',
      meta: 'CMR Institute of Technology, Bengaluru',
      detail: 'CGPA 8.66',
    },
    {
      year: '2022',
      label: 'Pre-University Course - Science (PCMB)',
      meta: "St Joseph's Pre University College, Bengaluru",
      detail: '83.3%',
    },
    {
      year: '2020',
      label: '10th Grade - ICSE',
      meta: 'Cambridge School, Bengaluru',
      detail: '81.8%',
    },
  ],
  experience: [
    {
      year: 'Jan 2026 - May 2026',
      label: 'Data Scientist Intern',
      meta: 'Cheerans Global Solutions Pvt Ltd.',
      detail: 'Frontend for cafe billing software, data analysis, data cleaning, and interactive dashboards.',
    },
  ],
}

export const stackGroups = [
  {
    id: 'AI',
    title: 'AI / ML',
    items: ['TensorFlow', 'OpenCV', 'NLP', 'Hugging Face', 'LLMs', 'Computer Vision'],
    related: ['CardioGuard', 'Operation Gridlock', 'Frame Your Goa'],
  },
  {
    id: 'WEB',
    title: 'Full-stack',
    items: ['React', 'Next.js', 'Node.js', 'Express', 'HTML'],
    related: ['JourneySync', 'Frame Your Goa', 'WorkState'],
  },
  {
    id: 'DATA',
    title: 'Data',
    items: ['Python', 'SQL', 'Pandas', 'PowerBI', 'Tableau', 'Jupyter'],
    related: ['Operation Gridlock', 'CardioGuard', 'Cheerans dashboards'],
  },
  {
    id: 'MOBILE',
    title: 'Mobile',
    items: ['Flutter', 'Android Studio', 'TensorFlow Lite'],
    related: ['JourneySync', 'AquaFlow', 'CardioGuard'],
  },
  {
    id: 'SYSTEMS',
    title: 'Automation',
    items: ['n8n', 'Flask', 'FAISS', 'Git', 'GitHub', 'Azure'],
    related: ['WorkState', 'AquaFlow', 'Frame Your Goa'],
  },
]
